### ISSUE TITLE
# PA Review: Document upload, storage, and download

### ISSUE THREAD

**Issue by philgresh** [philgresh/signdocs#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

## Functionality

- [x] User can view an `index` page of all documents (`/documents`)
  - [x] Each item in the list links to that document's `show` page
  - [x] Each item in the list shows some basic information about the document
  - [x] Page is styled
    - [x] The page has a header
    - [x] If no documents are available, a prompt is shown instead to create one (requires deleting seed data)
- [x] Each document has a `show` page (`/documents/:docId`)
  - [x] The page displays user-entered information about the document
  - [x] The page has a button to view/download the document
    - [x] The generated link expires after 5 minutes
  - [x] If the user is the owner of the document:
    - [x] The page has a link to the `edit` page for that document
    - [x] The page has a button to delete the document
      - [x] Clicking the delete button displays an alert for confirmation
      - [x] Rejecting the confirmation does not run the deletion
      - [x] Confirming the delete redirects the user to the `index` page
  - [x] Page is styled
- [x] User can create a new document (`/documents/new`)
  - [x] Submitting a document successfully redirects the user to the `show` page
  - [x] Page is styled
    - [x] Required/optional fields are clearly marked
    - [x] Errors are shown by the appropriate field
    - [x] On click, submit button is disabled and displays a 'loading' state
- [x] User can edit an existing document that they own (`/documents/:docId/edit`)
  - [x] Page reuses form for `create`
  - [x] Edits limited to `title`, `description` (i.e. not uploading a new file)
- [x] Files are hosted by AWS S3
  - [x] [Production S3 bucket](https://signdocs-ckdpd50m50000map7rw28508g-prod.s3-us-west-1.amazonaws.com/) is not publicly accessible
~~Document owners can create longer-expiration presigned urls to share with external parties~~
- [x] Signed-out users do not have access to `/documents` or its children (test with Postman)
- [x] Signed-out users cannot create or destroy documents (test with Postman)

### TODO to improve upon the above

- [ ] Add a modal to confirm document deletions
- [ ] Add a drag-and-drop area to add a file to a document
- [ ] The `show` page has a button to create a publicly-visible link to the document file
- [x] The `create`/`edit` page form fields should be validated
  - [x] Client-side validation prevents unnecessary post requests
  - [ ] Filesize/filetype restrictions are clearly marked
  - [x] Until validated, submit button is disabled
- [ ] Dropzone for file upload

**Comment by Vanchen07** [comment]
- I get the following console error:
![Screen Shot 2020-08-24 at 9 33 35 AM](https://user-images.githubusercontent.com/45908473/91071340-e7124c00-e5ec-11ea-86ca-803961367982.png)
- how do I create longer-expiration presigned urls?

**Comment by philgresh** [comment]
>     * how do I create longer-expiration presigned urls?
Whoops, meant to delete that line (I had added it as a bonus feature at the bottom)

>     * I get the following console error:
I haven't seen that or been able to replicate it :S

**Comment by Vanchen07** [comment]
Hm ok, maybe it's just my browser then. Otherwise excluding the bonus, this looks good!
