### ISSUE TITLE
PA Review: Signature creation

### ISSUE THREAD

**Issue by philgresh** [philgresh/signdocs#5]
# PA Review: Signature creation

- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

## Functionality

- [x] All users have a default signature created based on their name (given on sign-up) and is initially a random font
- [x] User can view a signature component on their profile page (`/profile`) 
  - [x] User can access this page from a drop-down menu or clicking on their signature on the main page
  - [x] User can edit their own signature on that page (no explicit `edit` route)
- [x] User can draw a likeness of their signature using a mouse
  - [x] User can clear a drawing of a signature
- [x] User can choose a font/style to act as their signature
  - [x] Fonts must be open-licensed
- [x] Signatures are persisted throughout the session and saved to the database
- [x] Signature "seals" bear the fingerprint of the user's unique cryptographic key

### TODO to improve upon the above

- [ ] Add a modal for this component
- [ ] Add a feature to erase part of a drawing or undo
- [ ] Add a color picker to customize the color of the signature

**Comment by philgresh** [comment]
Running into error after pushing to Heroku, working to resolve: `Aws::KMS::Errors::AccessDeniedException: An error occurred (AccessDeniedException) when calling the CreateKey operation: You don't have the kms:TagResource permission that is required to add tags during key creation.
from /app/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.104.3/lib/seahorse/client/plugins/raise_response_errors.rb`

**Comment by philgresh** [comment]
> Running into error after pushing to Heroku, working to resolve: `Aws::KMS::Errors::AccessDeniedException: An error occurred (AccessDeniedException) when calling the CreateKey operation: You don't have the kms:TagResource permission that is required to add tags during key creation. from /app/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.104.3/lib/seahorse/client/plugins/raise_response_errors.rb`

**RESOLVED**
I ended up not having to change any permissions for my AWS user. Must have been related to something else that was otherwise resolved.

**Comment by Vanchen07** [comment]
- wow this is so cool! Had so much fun creating my signature. Re: Signature "seals" bear the fingerprint of the user's unique cryptographic key, I'm assuming this is under the hood for the signature I created.

**Comment by philgresh** [comment]
Thanks Vanessa!

>  Re: Signature "seals" bear the fingerprint of the user's unique cryptographic key, I'm assuming this is under the hood for the signature I created.
Correct...when a user is initialized, an AWS public key is created for them and sits on AWS servers. I haven't implemented much with that yet, but the "fingerprint" is an MD5 hash of the public key. So eventually the idea is that the fingerprint verifies the authenticity of a user's seal :)
